name: Update badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make temp working directory
        run: |
          mkdir -p .tmp

      - name: Download custom integration analytics file
        run: |
          curl -s https://analytics.home-assistant.io/custom_integrations.json --output .tmp/custom_integrations.json

      - name: Download badges for integrations
        run: |
          integrations=(
            huawei_mesh_router
            tplink_easy_smart
            hass_yt_dlp
          )

          for integration in "${integrations[@]}"
          do
            installations=$(jq --arg integration "${integration}" '.[$integration].total' .tmp/custom_integrations.json)
            if [ "${installations}" != "null" ]
            then
              echo "Integration ${integration} has ${installations} installations:"
              versions=$(jq -c -r --arg integration "${integration}" '.[$integration].versions | keys | .[]' .tmp/custom_integrations.json)
              readarray -t versions_array <<< "${versions}"           
              for version in "${versions_array[@]}"
              do
                version_installations=$(jq --arg integration "${integration}" --arg version "${version}"  '.[$integration].versions[$version]' .tmp/custom_integrations.json)
                echo "  * version ${version} has ${version_installations} installations"
                curl -s "https://img.shields.io/badge/Active_installations_v{$version}-${version_installations}-blue" --output "${integration}-${version}.svg"
              done
            else
              installations="0"
              echo "Integration ${integration} has no installations."
            fi
            curl -s "https://img.shields.io/badge/Active_installations-${installations}-yellowgreen" --output "${integration}.svg"
          done

      - name: Remove temp working directory
        run: |
          rm -rf .tmp

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
